apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
      
resources:
  - ../../base
  - postgres.yaml
  - Ingress.yaml
  - keycloak.yaml
  - Services.yaml

helmCharts:
  - name: jaegertracing
    version: 4.0.0
    repo: https://jaegertracing.github.io/helm-charts
    releaseName: jaegertracing/jaeger
    namespace: keycloak

patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: keycloak-k8tre-tls